
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-backend
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"